



services:


  jenkins:
    build: ./jenkins
  

    ports:
      - "8080:8080"
      - "50000:50000" 
      
    privileged: true
    
    user: root
    

    
    volumes:
      - ./jenkins/.jen:/var/jenkins_home


  graphdb:
    build: ./graphdb
   
    ports:
      - "7200:7200"

  db:
    build: ./mysql
 
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: hybrid
        MYSQL_USER: user
        MYSQL_PASSWORD: pass
    ports:
      - "42333:3306"


  
    

